# To create the conda environment:
# $ conda env create -n my_env_name -f conda.yaml
#
# To update the conda environment:
# $ conda env update -n my_env_name -f conda.yaml
#
# To register the conda environment in Jupyter:
# $ python -m ipykernel install --user --name my_env_name --display-name "Python (my_env_name)"
#

channels:
- conda-forge
- defaults
dependencies:
- python==3.5
- numpy==1.14.5
- ipykernel==4.6.1
- cython==0.28.3
- pip:
  - scikit-learn==0.19.1
  - tornado==4.5.3
  - jupyter==1.0.0
  - matplotlib==2.1.2




